channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=21.2.4
- pip:
  - mlflow==2.11.1
  - cloudpickle==3.0.0
  - importlib-metadata==7.0.1
  - numpy==1.22.3
  - packaging==21.3
  - psutil==5.9.1
  - pyyaml==6.0.1
  - scikit-learn==1.1.0
  - scipy==1.8.0
name: mlflow-env
